remove agent detecting

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -2,12 +2,12 @@
 
 BUILD_DIR=$1
 
-if [ -f $BUILD_DIR/bin/agent ]; then
-  echo "Agent binary detected."
-else
-  echo "Missing agent binary."
-  exit 1
-fi
+# if [ -f $BUILD_DIR/bin/agent ]; then
+#   echo "Agent binary detected."
+# else
+#   echo "Missing agent binary."
+#   exit 1
+# fi
 
 if [ -f $BUILD_DIR/config/graphana-agent.yml ]; then
   echo "Agent config detected."
